pyerp/urls.py
"""Rutas de PyErp
"""
# Librerias Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views.static import serve

# Librerias de terceros
from apps.base.views import ActivateLanguageView

urlpatterns = [
    path('', include('apps.base.home_urls')),
    path('admin/', admin.site.urls),
    path('base/', include('apps.base.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT, }),
    # path('', include('apps.home.urls')),
]

urlpatterns += i18n_patterns(
    # path('', include('apps.base.home_urls')),
    # path('base/', include('apps.base.urls')),
    # path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path(
        '<language_code>/language/activate/',
        ActivateLanguageView.as_view(),
        name='activate_language'
    ),
)


with open('installed_apps.py', 'r') as ins_apps_file:
    for line in ins_apps_file.readlines():
        if line.strip() == 'apps.home':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.home.urls'))]
        else:
            _, app = line.split('.')
            urlpatterns += [path('%s/' % app.rstrip('\n'), include('%s.urls' % line.strip()))]

apps/base/models/usercustom.py
# -*- coding: utf-8
"""
Modelo de datos de la app globales
"""
# Librerias Future
from __future__ import unicode_literals

# Librerias Standard
import os

# Librerias Django
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

# Librerias en carpetas locales
from ..sobre_escribir_imagen import SobreEscribirImagen


def image_path(instance, filename):
    return os.path.join('avatar', str(instance.pk) + '.' + filename.rsplit('.', 1)[1])


class PyUser(AbstractUser):
    '''Modelo de los usuarios
    '''
    SEXO_CHOICES = (
        ('F', _('FEMALE')),
        ('M', _('MALE')),
    )
    LETRACEDULA_CHOICES = (
        ('V', 'V'),
        ('E', 'E'),
    )
    password = models.CharField(_("Password"), max_length=128)
    last_login = models.DateTimeField(_("Last login"), default=timezone.now)
    is_superuser = models.BooleanField(_("Super Admin"), default=False, db_index=True)
    is_staff = models.BooleanField(_("Staff"), default=False, db_index=True)
    is_active = models.BooleanField(_("Active"), default=False)
    username = models.CharField(_("User name"), max_length=150, db_index=True, unique=True)
    first_name = models.CharField(_("Name"), max_length=30)
    last_name = models.CharField(_("Last name"), max_length=30)
    email = models.CharField(_("Email"), max_length=254, null=False, db_index=True, unique=True)
    telefono = models.CharField(_("Phone"), max_length=255, blank=True, null=True)
    celular = models.CharField(_("Mobile Phone"), max_length=255, blank=True, null=True)
    fecha_nacimiento = models.DateField(_("Birthdate"), blank=True, null=True)
    sexo = models.CharField(_("Sex"), max_length=255, choices=SEXO_CHOICES, blank=True, null=True)
    avatar = models.ImageField(max_length=255, storage=SobreEscribirImagen(), upload_to=image_path, blank=True, null=True, default='avatar/default_avatar.png')

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    class Meta:
        verbose_name = _('Person')
        verbose_name_plural = _('People')
        db_table = 'auth_user'

apps/base/views/passwordchange.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación globales
"""

# Librerias Django
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, render
from django.utils.translation import ugettext_lazy as _


# ========================================================================== #
def cambio_clave(request):
    """Esta función es para el cambio de clave del usuario
    """
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Importante!
            messages.success(request, _('Your password change was successfully \
                processed'))
            return redirect('base:profile')
    else:
        form = PasswordChangeForm(request.user)
    return render(
        request,
        'usercustom/password_change_form.html',
        {'form': form}
    )

apps/base/views/passwordreset.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación globales
"""

# Librerias Django
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _

# Librerias de terceros
import requests

# Librerias en carpetas locales
from ..forms import PasswordRecoveryForm, PasswordSetForm
from ..models import PyUser
from ..tokens import PASSWORD_RECOVERY_TOKEN


# ========================================================================== #
class PasswordRecoveryView(PasswordResetView):
    """Esta Clase tiene dos funciones:
    1.- Envía un coreo al uuario con instrucciones para recuperar su
    contraseña
    2.- Despliega un formulario para recuperar la contraseña
    """
    success_url = 'base:login'
    template_name = 'usercustom/password_reset_form.html'
    extra_context = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'uidb64' in self.kwargs and 'token' in self.kwargs:
            # Formulario para escribir la nueva contraseña
            context['form'] = PasswordSetForm()
            context['url_action'] = reverse_lazy(
                'base:password-set',
                kwargs={
                    'uidb64': self.kwargs['uidb64'],
                    'token': self.kwargs['token']
                }
            )
        else:
            # Fromulario para solicitar el link de recuperación de contraseña
            context['form'] = PasswordRecoveryForm()
            context['url_action'] = reverse_lazy('base:password-recovery')

        return context

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        self.object = None
        form = self.get_form()
        if 'uidb64' in self.kwargs and 'token' in self.kwargs:
            form = PasswordSetForm(request.POST)
        else:
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = requests.get(url, params=values, verify=True)
            result = data.json()

            if result['success']:
                self.extra_context['reCAPTCHA_error'] = ''
            else:
                self.extra_context['reCAPTCHA_error'] = _('Invalid reCAPTCHA')
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        """If the form is valid, redirect to the supplied URL."""
        if 'uidb64' in self.kwargs and 'token' in self.kwargs:
            uidb64 = self.kwargs['uidb64']
            token = self.kwargs['token']
            uid = force_text(urlsafe_base64_decode(uidb64))

            try:
                user = PyUser.objects.get(pk=uid)
            except (TypeError, ValueError, OverflowError, PyUser.DoesNotExist):
                user = None

            token_valid = PASSWORD_RECOVERY_TOKEN.check_token(user, token)

            if user is not None and token_valid:
                user.set_password(form.cleaned_data['password1'])
                user.is_active = True
                user.save()
                messages.success(
                    self.request,
                    _('Welcome back, your password has been successfully modified. Please log in using your credentials.')
                )
            else:
                messages.error(
                    self.request,
                    _('The password recovery link is invalid or has already been used.')
                )

            return HttpResponseRedirect(reverse_lazy(self.get_success_url()))
        else:
            email = form.cleaned_data['email']
            try:
                user = PyUser.objects.get(email=email)
            except (TypeError, ValueError, OverflowError, PyUser.DoesNotExist):
                user = None
            if user is not None:
                current_site = get_current_site(self.request)
                subject = _('%(app_name)s password recovery') % {
                    'app_name': settings.APP_NAME
                }

                url = reverse_lazy(
                    'base:password-set',
                    kwargs={
                        'uidb64': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': PASSWORD_RECOVERY_TOKEN.make_token(user)
                    }
                )

                message_body = _('You received this email because you requested that your password be reset to "%(app_name)s".\n\nPlease go to the following link to recover your password:\n\nhttp://%(domain)s%(url)s\n\nThe credentials of this link last for one (1) day.\n\nBest regards.\n\nThe %(app_name)s team.') % {'app_name': settings.APP_NAME, 'user': user.username, 'domain': current_site.domain, 'url': url}
                message_body = message_body.replace("  ", "")

                user.email_user(subject, message_body)

                messages.success(
                    self.request,
                    _('Instructions to recover your password in %(app_name)s were sent to the email account %(email)s') % {'app_name': settings.APP_NAME, 'email': email}
                )

                return HttpResponseRedirect(reverse_lazy(self.get_success_url()))

            else:
                messages.error(
                    self.request,
                    _('The email provided is not registered in %(app_name)s') % {
                        'app_name': settings.APP_NAME
                    }
                )

                return HttpResponseRedirect(
                    reverse_lazy('base:password-recovery')
                )

apps/base/views/profile.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación globales
"""

# Librerias Django
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import UpdateView

# Librerias en carpetas locales
from ..forms import AvatarForm, PerfilForm
from ..models import PyUser


# ========================================================================== #
class ProfileView(SuccessMessageMixin, UpdateView):
    """Vista para editarar las sale
    """
    model = PyUser
    form_class = PerfilForm
    template_name = 'usercustom/profile.html'
    success_message = _('Your profile was updated successfully')
    success_url = reverse_lazy('base:profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_avatar'] = AvatarForm(instance=self.request.user)

        return context

    def get_object(self, queryset=None):
        """
        Return the object the view is displaying.
        Require `self.queryset` and a `pk` or `slug` argument in the URLconf.
        Subclasses can override this to return any object.
        """
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        # pk = self.kwargs.get(self.pk_url_kwarg)
        pk = self.request.user.pk
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        if slug is not None and (pk is None or self.query_pk_and_slug):
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        if pk is None and slug is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(
                _("No %(verbose_name)s found matching the query") %
                {'verbose_name': queryset.model._meta.verbose_name}
            )
        return obj

apps/base/views/signup.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación globales
"""

# Librerias Django
from django.conf import settings
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView

# Librerias de terceros
import requests

# Librerias en carpetas locales
from ..forms import PersonaCreationForm
from ..models import PyUser
from ..tokens import ACCOUNT_ACTIVATION_TOKEN


##############################################################################
class SignUpView(CreateView):
    """Esta clase sirve registrar a los usuarios en el sistema
    """
    model = PyUser
    form_class = PersonaCreationForm
    template_name = 'usercustom/signup.html'
    extra_context = {}
    success_url = 'base:login'
    success_message = _('Your account was created successfully. A link was sent to your email that you must sign in to confirm your sign up.')

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        self.object = None
        form = self.get_form()
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = requests.get(url, params=values, verify=True)
        result = data.json()

        if form.is_valid() and result['success']:
            self.extra_context['reCAPTCHA_error'] = ''
            return self.form_valid(form)
        else:
            if not result['success']:
                self.extra_context['reCAPTCHA_error'] = _('Invalid reCAPTCHA')
            return self.form_invalid(form)

    def form_valid(self, form):
        """If the form is valid, redirect to the supplied URL."""
        self.object = form.save()
        current_site = get_current_site(self.request)
        subject = _('%(app_name)s sign up') % {'app_name': settings.APP_NAME}

        url = reverse_lazy(
            'base:activar',
            kwargs={
                'uidb64': urlsafe_base64_encode(force_bytes(self.object.pk)),
                'token': ACCOUNT_ACTIVATION_TOKEN.make_token(self.object)
            }
        )

        message_body = _('Thank you for registering in %(app_name)s, your username is: %(user)s.\n\nPlease go to the following link to confirm your registration and activate your account:\n\nhttp://%(domain)s%(url)s\n\nThe credentials of this link last for one (1) day.\n\nBest regards.\n\nThe %(app_name)s team.') % {'app_name': settings.APP_NAME, 'user': self.object.username, 'domain': current_site.domain, 'url': url}
        message_body = message_body.replace("  ", "")

        self.object.email_user(subject, message_body)

        messages.success(
            self.request,
            _('Your account has been created successfully. Open the link that was sent to your email, to confirm your registration and activate your account.')
        )

        return HttpResponseRedirect(reverse_lazy(self.get_success_url()))

apps/usercustom/templates/usercustom/profile.html
{% extends "base/dashboard.html" %}
{% block stylesheets %}
    <!-- Cropper JS -->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/cropper.css">
    <!-- Tempus Dominus -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    {{ form.media }}

    <style>
      .label {
        cursor: pointer;
        padding: 0px;
      }

      .progress {
        display: none;
        margin-bottom: 1rem;
      }

      .img-container img {
        max-width: 100%;
      }
    </style>
{% endblock stylesheets %}

{% block content %}
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <!-- Profile Image -->
                        <div class="card card-primary card-outline">
                            <div class="card-body box-profile">
                                <div class="text-center">
                                    <label class="label" data-toggle="tooltip" title="Change your avatar">
                                        <img class="profile-user-img img-fluid img-circle" id="avatar_img" src="{{ request.user.avatar.url }}" alt="{{ request.user }}">
                                        <form method="post" enctype="multipart/form-data" action="{% url 'usercustom:avatar' %}" id="formUpload">
                                            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                                            <input type="file" class="sr-only" id="id_avatar" name="avatar" accept="image/*">
                                        </form>
                                    </label>
                                </div>
                                <h3 class="profile-username text-center">{{ user }}</h3>
                                <a href="{% url 'usercustom:change-password'  %}" class="btn btn-primary btn-block"><b>{{ _('Change Password') }}</b></a>
                            </div><!-- /.card-body -->
                        </div><!-- /.card -->
                    </div><!-- /.col -->
                    <div class="col-md-9">
                        <!-- Profile Image -->
                        <div class="card">
                            <div class="card-body">
                                <form class="form-horizontal" action="{% url 'usercustom:profile' %}" method="post" role="form">
                                    {% csrf_token %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% for field in form.visible_fields %}
                                        {% if forloop.counter0|divisibleby:"2" or forloop.counter0 == 0 %}
                                            <div class="row">
                                        {%endif%}
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="id_first_name">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        <!-- /.col -->
                                        </div>
                                        {% if forloop.counter|divisibleby:"2" or forloop.last == true %}
                                            </div>
                                            <!-- /.row -->
                                        {%endif%}
                                    {% endfor %}
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <button type="submit" class="btn btn-danger float-right">{{ _('Submit') }}</button>
                                        </div>
                                    </div>
                                </form>
                            </div><!-- /.card-body -->
                        </div><!-- /.card -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
            <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalLabel">{{ _('Crop the image') }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            <div class="img-container"><img id="image" src="{{ request.user.avatar.url }}"></div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('Cancel') }}</button>
                            <button type="button" class="btn btn-primary" id="crop">{{ _('Crop') }}</button>
                        </div>
                    </div>
                </div>
            </div><!-- /.modal -->
{% endblock content %}
{% block javascripts %}
    <!-- cropper 4.0.0 -->
    <script src="{{ STATIC_URL }}js/cropper.js"></script>
    <!-- page script -->
    <script type="text/javascript">
        $(document).ready(function () {
            toastr.options.closeButton = true
            toastr.options.timeOut = 11000
            toastr.options.preventDuplicates = true
            toastr.options.progressBar = true

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        toastr.error("{{ error|escape }}")
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    toastr.error("{{ error|escape }}")
                {% endfor %}
            {% endif %}

            {% if next %}
                {% if request.user.is_authenticated %}
                    toastr.warning("{{ _('Your account does not have the necessary privileges to access this section. To continue, log in with an account that has the necessary privileges.') }}")
                {% else %}
                    toastr.info("{{ _('Please login to visit this page.') }}")
                {% endif %}
            {% endif %}

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'debug' %}toastr.info("{{ message }}"){% endif %}
                    {% if message.tags == 'info' %}toastr.info("{{ message }}"){% endif %}
                    {% if message.tags == 'success' %}toastr.success("{{ message }}"){% endif %}
                    {% if message.tags == 'warning' %}toastr.warning("{{ message }}"){% endif %}
                    {% if message.tags == 'error' %}toastr.error("{{ message }}"){% endif %}
                {% endfor %}
            {% endif %}
        });

        // Script para cortar el avatar con crop.js
        window.addEventListener('DOMContentLoaded', function () {
            var avatar = document.getElementById('avatar_img');
            var user_avatar = document.getElementById('user_avatar');
            var image = document.getElementById('image');
            var input = document.getElementById('id_avatar');
            var $progress = $('.progress');
            var $progressBar = $('.progress-bar');
            var $alert = $('.alert');
            var $modal = $('#modal');
            var cropper;
            var csrftoken = $("[name=csrfmiddlewaretoken]").val();

            $('[data-toggle="tooltip"]').tooltip();

            input.addEventListener('change', function (e) {
                var files = e.target.files;
                var done = function (url) {
                    input.value = '';
                    image.src = url;
                    $alert.hide();
                    $modal.modal('show');
                };
                var reader;
                var file;
                var url;

                if (files && files.length > 0) {
                    file = files[0];

                    if (URL) {
                        done(URL.createObjectURL(file));
                    } else if (FileReader) {
                        reader = new FileReader();
                        reader.onload = function (e) {
                            done(reader.result);
                        };
                        reader.readAsDataURL(file);
                    }
                }
            });

            $modal.on('shown.bs.modal', function () {
                cropper = new Cropper(image, {
                    aspectRatio: 1,
                    viewMode: 3,
                });
            }).on('hidden.bs.modal', function () {
                cropper.destroy();
                cropper = null;
            });

            document.getElementById('crop').addEventListener('click', function () {
                var initialAvatarURL;
                var canvas;

                $modal.modal('hide');

                if (cropper) {
                    canvas = cropper.getCroppedCanvas({width: 160, height: 160,});
                    initialAvatarURL = avatar.src;
                    avatar.src = canvas.toDataURL(); //Altero el avatar del perfil
                    user_avatar.src = canvas.toDataURL(); //Altero el avatar de la barra superior
                    $progress.show();
                    $alert.removeClass('alert-success alert-warning');
                    canvas.toBlob(function (blob) {
                        var formData = new FormData();

                        formData.append('avatar', blob, 'avatar.jpg');
                        $.ajax('{% url 'usercustom:avatar' %}', {
                            method: 'POST',
                            headers:{"X-CSRFToken": csrftoken},
                            data: formData,
                            processData: false,
                            contentType: false,

                            xhr: function () {
                                var xhr = new XMLHttpRequest();

                                xhr.upload.onprogress = function (e) {
                                    var percent = '0';
                                    var percentage = '0%';

                                    if (e.lengthComputable) {
                                        percent = Math.round((e.loaded / e.total) * 100);
                                        percentage = percent + '%';
                                        $progressBar.width(percentage).attr('aria-valuenow', percent).text(percentage);
                                    }
                                };

                                return xhr;
                            },

                            success: function () {
                            },

                            error: function () {
                                avatar.src = initialAvatarURL;
                            },

                            complete: function () {
                              $progress.hide();
                            },
                        });
                        return false;
                    });
                }
            });
        });
    </script>
{% endblock javascripts %}