apps/base/urls.py
# Librerias Django
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

# Librerias en carpetas locales
from .views import (
    ActivateView, AvatarUpdateView, ChangePasswordForm, ChangePasswordView,
    CompanyCreateView, CompanyDetailView, CompanyListView, CompanyUpdateView,
    CustomerListView, DeleteCompany, DeletePartner, DeleteUser,
    DoChangePassword, InstallApps, LogOutModalView, PartnerAutoComplete,
    PartnerCreateView, PartnerDetailView, PartnerUpdateView,
    PasswordRecoveryView, ProfileView, ProviderListView, SignUpView,
    UninstallApps, UpdateApps, UpdateBaseConfigView, UserCreateView,
    UserDetailView, UserListView, UserUpdateView, erp_home)
from .views.app import AppView
from .views.base_config import LoadData
from .views.country import (
    CountryCreateView, CountryDetailView, CountryListView, CountryUpdateView,
    DeleteCountry)
from .views.cron import (
    CronCreateView, CronDetailView, CronListView, CronUpdateView, DeleteCron)
from .views.currency import (
    CurrencyCreateView, CurrencyDetailView, CurrencyListView,
    CurrencyUpdateView, DeleteCurrency)
from .views.log import (
    DeleteLog, LogCreateView, LogDetailView, LogListView, LogUpdateView)
# from .views.logoutmodal import LogOutModalView
from .views.product import (
    DeleteProduct, ProductCreateView, ProductDetailView, ProductListView,
    ProductUpdateView)
from .views.product_category import (
    DeleteProductCategory, ProductCategoryCreateView,
    ProductCategoryDetailView, ProductCategoryListView,
    ProductCategoryUpdateView)
from .views.product_webcategory import (
    DeleteProductWebCategory, ProductWebCategoryCreateView,
    ProductWebCategoryDetailView, ProductWebCategoryListView,
    ProductWebCategoryUpdateView)

app_name = 'base'

urlpatterns = [
    path('', erp_home, name='home'),
    # path(
    #     'login/',
    #     auth_views.LoginView.as_view(template_name='login.html'),
    #     name='login'
    # ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='base/login.html'),
        name='logout'
    ),
    # path('logoutmodal/', LogOutModalView.as_view(), name='logout-modal'),
    path('config/<int:pk>', UpdateBaseConfigView.as_view(), name='base-config'),
    path('load-data', LoadData, name='load-data'),


    path('update-app', UpdateApps, name='update-app'),
    path('install-app/<int:pk>/', InstallApps, name='install-app'),
    path('uninstall-app/<int:pk>/', UninstallApps, name='uninstall-app'),


    path('users', UserListView.as_view(), name='users'),
    path('user/add/', UserCreateView.as_view(), name='user-add'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', DeleteUser, name='user-delete'),
    path('user/change-password/<int:pk>', ChangePasswordForm, name='password-change'),
    path('user/change-password-confirm/<int:pk>', DoChangePassword, name='do-change-password'),

    path('products', ProductListView.as_view(), name='products'),
    path('product/add/', ProductCreateView.as_view(), name='product-add'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('Product/<int:pk>/update', ProductUpdateView.as_view(), name='product-update'),
    path('Product/<int:pk>/delete/', DeleteProduct, name='product-delete'),


    path('countries', CountryListView.as_view(), name='countries'),
    path('country/add/', CountryCreateView.as_view(), name='country-add'),
    path('country/<int:pk>/', CountryDetailView.as_view(), name='country-detail'),
    path('country/<int:pk>/update', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', DeleteCountry, name='country-delete'),

    path('companies', CompanyListView.as_view(), name='companies'),
    path('company/add/', CompanyCreateView.as_view(), name='company-add'),
    path('company/<int:pk>/', CompanyDetailView.as_view(), name='company-detail'),
    path('company/<int:pk>/update', CompanyUpdateView.as_view(), name='company-update'),
    path('company/<int:pk>/delete/', DeleteCompany, name='company-delete'),

    path('partners', CustomerListView.as_view(), name='partners'),
    path('provider', ProviderListView.as_view(), name='provider'),

    path('partner/add/', PartnerCreateView.as_view(), name='partner-add'),
    path('partner/<int:pk>/', PartnerDetailView.as_view(), name='partner-detail'),
    path('partner/<int:pk>/update', PartnerUpdateView.as_view(), name='partner-update'),
    path('partner/<int:pk>/delete/', DeletePartner, name='partner-delete'),

    path('product-category', ProductCategoryListView.as_view(), name='product-category'),
    path('product-category/add/', ProductCategoryCreateView.as_view(), name='product-category-add'),
    path('product-category/<int:pk>/', ProductCategoryDetailView.as_view(), name='product-category-detail'),
    path('product-category/<int:pk>/update', ProductCategoryUpdateView.as_view(), name='product-category-update'),
    path('product-category/<int:pk>/delete/', DeleteProductCategory, name='product-category-delete'),

    path('product-webcategory', ProductWebCategoryListView.as_view(), name='product-webcategory'),
    path('product-webcategory/add/', ProductWebCategoryCreateView.as_view(), name='product-webcategory-add'),
    path('product-webcategory/<int:pk>/', ProductWebCategoryDetailView.as_view(), name='product-webcategory-detail'),
    path('product-webcategory/<int:pk>/update', ProductWebCategoryUpdateView.as_view(), name='product-webcategory-update'),
    path('product-webcategory/<int:pk>/delete/', DeleteProductWebCategory, name='product-webcategory-delete'),

    path('logs', LogListView.as_view(), name='logs'),
    path('log/add/', LogCreateView.as_view(), name='log-add'),
    path('log/<int:pk>/', LogDetailView.as_view(), name='log-detail'),
    path('log/<int:pk>/update', LogUpdateView.as_view(), name='log-update'),
    path('log/<int:pk>/delete/', DeleteLog, name='log-delete'),

    path('crons', CronListView.as_view(), name='crons'),
    path('cron/add/', CronCreateView.as_view(), name='cron-add'),
    path('cron/<int:pk>/', CronDetailView.as_view(), name='cron-detail'),
    path('cron/<int:pk>/update', CronUpdateView.as_view(), name='cron-update'),
    path('cron/<int:pk>/delete/', DeleteCron, name='cron-delete'),

    path('currencies', CurrencyListView.as_view(), name='currencies'),
    path('currency/add/', CurrencyCreateView.as_view(), name='currency-add'),
    path('currency/<int:pk>/', CurrencyDetailView.as_view(), name='currency-detail'),
    path('currency/<int:pk>/update', CurrencyUpdateView.as_view(), name='currency-update'),
    path('currency/<int:pk>/delete/', DeleteCurrency, name='currency-delete'),


    path('apps', AppView.as_view(), name='apps'),

    # ====================== Rutas de Auto Completado ====================== #
    path(
        'partner/partner-autocomplete',
        PartnerAutoComplete.as_view(),
        name='partners-autocomplete'
    ),

    path('signup', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>', ActivateView.as_view(), name='activar'),
    path(
        'login/',
        LoginView.as_view(
            template_name='usercustom/login.html',
            # redirect_field_name='next',
            success_url = 'home'
        ),
        name='login'
    ),
    path(
        'logout',
        LogoutView.as_view(next_page='base:login'),
        name='logout'
    ),
    path('logoutmodal/', LogOutModalView.as_view(), name='logout-modal'),
    path('profile', login_required(ProfileView.as_view()), name='profile'),
    path(
        'changepasword',
        login_required(ChangePasswordView),
        name='change-password'
        ),
    path(
        'password-recovery',
        PasswordRecoveryView.as_view(),
        name='password-recovery'
    ),
    path(
        'password-recovery/<uidb64>/<token>',
        PasswordRecoveryView.as_view(),
        name='password-set'
    ),
    path('avatar', login_required(AvatarUpdateView.as_view()), name='avatar'),
]

apps/sale/urls.py
"""Rutas del módulo de ordenes de venta
"""
# Librerias Django
from django.urls import path

# Librerias de terceros
from .reports.saleorderpdf import sale_order_pdf
from .views import (
    SaleOrderAddView, SaleOrderDeleteView, SaleOrderDetailAddView,
    SaleOrderDetailDeleteView, SaleOrderDetailEditView, SaleOrderEditView,
    SaleOrderListView, ProductAutoComplete)

app_name = 'sale'

urlpatterns = [
    # ========================== Sale Orders URL's ========================= #
    path('sale-order', SaleOrderListView.as_view(), name='sale-order'),
    path('sale-order/add/', SaleOrderAddView.as_view(), name='sale-order-add'),
    path(
        'sale-order/edit/<int:pk>',
        SaleOrderEditView.as_view(),
        name='sale-order-edit'
    ),
    path(
        'sale-order/delete/<int:pk>',
        SaleOrderDeleteView.as_view(),
        name='sale-order-delete'
    ),
    # ====================== Sale Orders Detail URL's ====================== #
    path(
        'sale-order-detail/add/<int:saleorder_pk>',
        SaleOrderDetailAddView.as_view(),
        name='sale-order-detail-add'
    ),
    path(
        'sale-order-detail/edit/<int:pk>',
        SaleOrderDetailEditView.as_view(),
        name='sale-order-detail-edit'
    ),
    path(
        'sale-order-detail/delete/<int:pk>',
        SaleOrderDetailDeleteView.as_view(),
        name='sale-order-detail-delete'
    ),
    # ====================== Sale Orders Reports URL's ===================== #
    path(
        'sale-order-pdf/<int:pk>',
        sale_order_pdf,
        name='sale-order-pdf'
    ),
    # ==================== Auto completado de Productos ==================== #
    path(
        'product-autocomplete',
        ProductAutoComplete.as_view(),
        name='product-autocomplete'
    ),
]

pyerp/urls.py
"""Rutas de PyErp
"""
# Librerias Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views.static import serve

# Librerias de terceros
from apps.base.views import ActivateLanguageView

urlpatterns = [
    path('', include('apps.base.home_urls')),
    path('admin/', admin.site.urls),
    path('base/', include('apps.base.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT, }),
    # path('', include('apps.home.urls')),
]

urlpatterns += i18n_patterns(
    # path('', include('apps.base.home_urls')),
    # path('base/', include('apps.base.urls')),
    # path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path(
        '<language_code>/language/activate/',
        ActivateLanguageView.as_view(),
        name='activate_language'
    ),
)


with open('installed_apps.py', 'r') as ins_apps_file:
    for line in ins_apps_file.readlines():
        if line.strip() == 'apps.home':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.home.urls'))]
        else:
            _, app = line.split('.')
            urlpatterns += [path('%s/' % app.rstrip('\n'), include('%s.urls' % line.strip()))]

apps/sale/views.py
# """Vistas para el módulo sale
# """
# # Librerias Django
# from django.shortcuts import render

# # Librerias en carpetas locales
# from .reports.saleorderpdf import sale_order_pdf
# from .subviews.saleorderadd import SaleOrderAddView
# from .subviews.saleorderdelete import SaleOrderDeleteView
# from .subviews.saleorderdetailadd import SaleOrderDetailAddView
# from .subviews.saleorderdetaildelete import SaleOrderDetailDeleteView
# from .subviews.saleorderdetailedit import SaleOrderDetailEditView
# from .subviews.saleorderedit import SaleOrderEditView
# from .subviews.saleorderlist import SaleOrderListView

apps/sale/views/saleorderadd.py
"""Sub Vistas del módulo
"""
# Librerias Standard
import logging

# Librerias Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.utils.translation import ugettext_lazy as _

# Librerias en carpetas locales
from ..forms import SaleOrderForm
from ..models import PySaleOrder

LOGGER = logging.getLogger(__name__)


# ========================================================================== #
class SaleOrderAddView(LoginRequiredMixin, CreateView):
    """Vista para agregar las sale
    """
    model = PySaleOrder
    form_class = SaleOrderForm
    template_name = 'sale/saleorderform.html'
    success_url = 'sale:sale-order-edit'

    def get_context_data(self, **kwargs):
        context = super(SaleOrderAddView, self).get_context_data(**kwargs)
        context['title'] = _('Sale Order Add')
        context['action_url'] = 'sale:sale-order-add'
        context['back_url'] = 'sale:sale-order'
        context['breadcrumbs'] = [{'url': 'sale:sale-order', 'name': _('Sales')}]

        return context

    def form_valid(self, form):
        self.object = form.save()
        url = reverse_lazy(self.get_success_url(), kwargs={'pk': self.object.pk})

        return HttpResponseRedirect(url)

apps/sale/views/saleorderdelete.py
"""Sub Vistas del módulo
"""
# Librerias Standard
import logging

# Librerias Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.utils.translation import ugettext_lazy as _

# Librerias en carpetas locales
from ..models import PySaleOrder, PySaleOrderDetail

LOGGER = logging.getLogger(__name__)


# ========================================================================== #
class SaleOrderDeleteView(LoginRequiredMixin, DeleteView):
    """Vista para eliminar las sale
    """
    model = PySaleOrder
    template_name = 'sale/saleorderdelete.html'
    success_url = reverse_lazy('sale:sale-order')

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg)
        self.object = self.get_object()
        context = super(SaleOrderDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'ELiminar Orden de Venta'
        context['action_url'] = 'sale:sale-order-delete'
        context['delete_message'] = '<p>¿Está seguro de eliminar la orden de compras <strong>' + self.object.name + '</strong>?</p>'
        context['cant_delete_message'] = '<p>La orden de compras <strong>' + self.object.name + '</strong>, no puede ser eliminada ya que posee un detalle que debe eliminar antes.</p>'
        context['detail'] = PySaleOrderDetail.objects.filter(sale_order=pk).exists()

        return context

    def delete(self, request, *args, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg)
        self.object = self.get_object()
        success_url = self.get_success_url()
        detail = PySaleOrderDetail.objects.filter(sale_order=pk).exists()
        if not detail:
            self.object.delete()

        return HttpResponseRedirect(success_url)

apps/sale/views/saleorderdetailadd.py
"""Sub Vistas del módulo
"""
# Librerias Standard
import logging

# Librerias Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.utils.translation import ugettext_lazy as _

# Librerias en carpetas locales
from ..forms import SaleOrderDetailForm
from ..models import PySaleOrder, PySaleOrderDetail

LOGGER = logging.getLogger(__name__)


# ========================================================================== #
class SaleOrderDetailAddView(LoginRequiredMixin, CreateView):
    """Vista para agregar las sale
    """
    model = PySaleOrderDetail
    form_class = SaleOrderDetailForm
    template_name = 'sale/saleordermodalform.html'
    success_url = 'sale:sale-order-edit'

    def get_context_data(self, **kwargs):
        context = super(SaleOrderDetailAddView, self).get_context_data(**kwargs)
        context['title'] = _('Add Product to the Sales Order')
        context['action_url'] = reverse_lazy(
            'sale:sale-order-detail-add',
            kwargs={'saleorder_pk': self.kwargs['saleorder_pk']}
        )
        context['sale_order_pk'] = self.kwargs['saleorder_pk']

        return context

    def get_initial(self):
        initial = super(SaleOrderDetailAddView, self).get_initial()
        initial.update({'sale_order': self.kwargs['saleorder_pk']})

        return initial

    def form_valid(self, form):
        """To Do:
            1.-Validar que la "order sale" este habilitada para poderle
            agregar más productos.
            2.- Otras validaciones concernientes a los calculos y la
            aplicación de impuestos y esas cosas.
        """
        _sale_order_pk = self.kwargs['saleorder_pk']
        self.object = form.save(commit=False)
        self.object.sale_order_id = _sale_order_pk
        self.object.amount_total = (
            self.object.amount_untaxed * self.object.quantity
        ) - self.object.discount
        self.object.save()
        url = reverse_lazy(
            self.get_success_url(),
            kwargs={'pk': _sale_order_pk}
        )

        return HttpResponseRedirect(url)

apps/sale/templates/sale/menu.html
<li class="nav-item has-treeview">
    <a href="#" class="nav-link">
      <i class="fa fa-file nav-icon"></i>
      <p>
        {{ _('Sale') }}
        <i class="fas fa-angle-left right"></i>
      </p>
    </a>
    <ul class="nav nav-treeview">

        <li class="nav-item">
          <a href="{% url 'sale:sale-order' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>{{ _('Quotation') }}</p>
          </a>
        </li>

      <li class="nav-item">
        <a href="{% url 'base:partners' %}" class="nav-link">
          <i class="far fa-circle nav-icon"></i>
          <p>{{ _('Clients') }}</p>
        </a>
      </li>
      <li class="nav-item">
          <a href="{% url 'base:products' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>{{ _('Products') }}</p>
          </a>
        </li>
    </ul>
  </li>

apps/sale/templates/sale/saleorderdelete.html
<div class="modal fade show" id="modal-danger" style="display: block; padding-right: 12px;" aria-modal="true">
    <div class="modal-dialog">
        <div class="modal-content bg-danger">
            <div class="modal-header">
                <h4 class="modal-title">{{ title }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                {% if not detail %}
                    {{ delete_message|safe }}
                    <p>{{ _('If you wish to continue press "Delete", keep in mind that this action is irreversible.') }}</p>
                    <p>{{ _('Press "Cancel" to cancel the action.') }}</p>
                {% else %}
                    {{ cant_delete_message|safe }}
                {% endif %}
            </div>
            <div class="modal-footer">
                <button class="btn btn-outline-light" type="button" data-dismiss="modal">{{ _('Cancel') }}</button>
                {% if not detail %}
                    <form class="form-horizontal" role="form" action="{% url action_url object.pk %}" method="post">
                    <form method="post" class="form">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light">{{ _('Delete') }}</button>
                    </form>
                {% endif %}
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

apps/sale/templates/sale/saleorderform.html
{% extends "base/dashboard.html" %}
{% load static %}
{% load erp_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/extensions/Buttons/css/buttons.dataTables.min.css' %}">
    <style>
        hr.line-divider{
            border-top: 1px solid #8c8b8b;
        }
    </style>
{% endblock %}
{% block content %}
    <form method="post" class="form">
        <div class="card card-primary card-outline mt-2">
            <div class="card-header">
                <a href="{% url back_url %}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> {{ _('Discard') }}</a>
                <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-save"></i> {{ _('Save') }}</button>
                {% if object %}
                    <a href="{% url print_url object.pk %}" class="btn btn-success btn-sm"><i class="fas fa-download"></i> {{ _('Print') }}</a>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {% for campo in form %}
                    <div class="form-group row">
                        <label for="{{ campo.id_for_label }}" class="col-sm-3 col-xl-2 col-form-label">{{ campo.label }}</label>
                        <div class="col-sm-9 col-xl-10">
                            {{ campo }}
                            <span class="help-block">
                                {% for error in campo.errors %}
                                    <ul>
                                        <li class="text-red">{{ error }}</li>
                                    </ul>
                                {% endfor %}
                            </span>
                        </div>
                    </div>
                {% endfor %}
                {% if object %}
                    <table id="list_table" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                        <thead>
                            <tr>
                                {% for field in fields %}
                                <th class="text-center">{{ field.string }}</th>
                                {% endfor %}
                                <th class="text-center col-sm-2">{{ _('Actions') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for element in object_list %}
                            <tr>
                                {% for field in fields %}
                                <td class="{{ field.align }}">{{ element|get_obj_attr:field.field }}</td>
                                {% endfor %}
                                <td class="text-center col-sm-2">
                                    <button onclick="return abrir_modal('{% url product_edit_url element.pk %}')" data-toggle="tooltip" title="Editar" type="button" class="btn btn-primary btn-sm"><span class="fa fa-pen"></span></button>
                                    <button onclick="return abrir_modal('{% url product_delete_url element.pk %}')" data-toggle="tooltip" title="Eliminar" type="button" class="btn btn-danger btn-sm"><span class="fa fa-trash"></span></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th class="col-12" colspan="12"><button class="btn text-primary" onclick="return abrir_modal('{% url product_add_url object.pk %}')" type="button" data-dismiss="modal">{{ _('Add Product')}}</button></th>
                            </tr>
                        </tfoot>
                    </table>
                {% endif %}
            </div>
            <!-- /.card-body -->
            {% if object %}
                <div class="card-footer">
                    <div class="row">
                        <div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _('Net Amount or Affection:') }}</div>
                        <div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right">$ {{ object.amount_untaxec }}</div>
                    </div>
                    <div class="row">
                        <div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _('Exempt Amount:') }}</div>
                        <div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right">$ {{ object.amount_taxt }}</div>
                    </div>
                    <div class="row">
                        <div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _('IVA:') }}</div>
                        <div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right">$ ???</div>
                    </div>
                    <div class="row">
                        <div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _('Other taxes:') }}</div>
                        <div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right">$ ???</div>
                    </div>
                    <div class="row">
                        <div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _('Total taxes:') }}</div>
                        <div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right">$ ???</div>
                    </div>
                    <hr class="style1">
                    <div class="row">
                        <div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _('Total:') }}</div>
                        <div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right">$ {{ object.amount_total }}</div>
                    </div>
                    <div class="row">
                        <div class="col col-sm-7 col-md-8 col-lg-9 col-xl-10 font-weight-bold text-right">{{ _('Margin:') }}</div>
                        <div class="col col-sm-5 col-md-4 col-lg-3 col-xl-2 text-right">$ ???</div>
                    </div>
                </div>
                <!-- /.card-footer -->
            {% endif %}
        </div>
        <!-- /.card -->
        {{ form.media.js }}
    </form>
{% endblock %}
{% block scripts %}
<script src="{% static 'plugins/datatables/jquery.dataTables.js'%}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap4.js'%}"></script>
<script src="{% static 'plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js'%}"></script>
<script src="{% static 'plugins/datatables/extensions/Buttons/js/buttons.flash.min.js'%}"></script>
<script src="{% static 'plugins/datatables/extensions/Buttons/js/buttons.html5.min.js'%}"></script>
<script src="{% static 'plugins/datatables/extensions/Buttons/js/buttons.print.min.js'%}"></script>
<script src="{% static 'plugins/datatables/extensions/pdfmake/pdfmake.min.js'%}"></script>
<script src="{% static 'plugins/datatables/extensions/pdfmake/vfs_fonts.js'%}"></script>
<script>
    $(document).ready(function () {
        var table = $('#example').DataTable({
            paging: false,
            lengthChange: true,
            searching: true,
            ordering: true,
            info: true,
            autoWidth: true,
            columnDefs: [
                { "targets": [0, 1, 2, 3], "orderable": false },
                { "targets": [0, 1, 2, 3], "searchable": false },
            ],
            language: {
                lengthMenu: "Mostrar _MENU_ registros por página",
                zeroRecords: "Lo sentimos, no encontramos nada",
                info: "Mostrando la página _PAGE_ de _PAGES_",
                infoEmpty: "Sin registros disponibles",
                infoFiltered: "(Filtrados de untotal de _MAX_ registros)",
                search: "Buscar: ",
                paginate: {
                    first: "Primero",
                    last: "Último",
                    next: "Siguiente",
                    previous: "Previo"
                },
                decimal: "-",
                thousands: "."
            },
            buttons: [
                {
                    extend: 'copyHtml5',
                    exportOptions: {
                        columns: [ 0, 1 ]
                    }
                },
                {
                    extend: 'csvHtml5',
                    exportOptions: {
                        columns: [ 0, 1 ]
                    }
                },
                {
                    extend: 'pdfHtml5',
                    exportOptions: {
                        columns: [ 0, 1 ]
                    }
                },
                'colvis'
            ]
        });
        table.buttons().container()
            .appendTo('#example_wrapper .col-sm-6:eq(0)');
    });
</script>
{% endblock %}