apps/base/urls.py
# Librerias Django
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

# Librerias en carpetas locales
from .views import (
    ActivateView, AvatarUpdateView, ChangePasswordForm, ChangePasswordView,
    CompanyCreateView, CompanyDetailView, CompanyListView, CompanyUpdateView,
    CustomerListView, DeleteCompany, DeletePartner, DeleteUser,
    DoChangePassword, InstallApps, LogOutModalView, PartnerAutoComplete,
    PartnerCreateView, PartnerDetailView, PartnerUpdateView,
    PasswordRecoveryView, ProfileView, ProviderListView, SignUpView,
    UninstallApps, UpdateApps, UpdateBaseConfigView, UserCreateView,
    UserDetailView, UserListView, UserUpdateView, erp_home)
from .views.app import AppView
from .views.base_config import LoadData
from .views.country import (
    CountryCreateView, CountryDetailView, CountryListView, CountryUpdateView,
    DeleteCountry)
from .views.cron import (
    CronCreateView, CronDetailView, CronListView, CronUpdateView, DeleteCron)
from .views.currency import (
    CurrencyCreateView, CurrencyDetailView, CurrencyListView,
    CurrencyUpdateView, DeleteCurrency)
from .views.log import (
    DeleteLog, LogCreateView, LogDetailView, LogListView, LogUpdateView)
# from .views.logoutmodal import LogOutModalView
from .views.product import (
    DeleteProduct, ProductCreateView, ProductDetailView, ProductListView,
    ProductUpdateView)
from .views.product_category import (
    DeleteProductCategory, ProductCategoryCreateView,
    ProductCategoryDetailView, ProductCategoryListView,
    ProductCategoryUpdateView)
from .views.product_webcategory import (
    DeleteProductWebCategory, ProductWebCategoryCreateView,
    ProductWebCategoryDetailView, ProductWebCategoryListView,
    ProductWebCategoryUpdateView)

app_name = 'base'

urlpatterns = [
    path('', erp_home, name='home'),
    # path(
    #     'login/',
    #     auth_views.LoginView.as_view(template_name='login.html'),
    #     name='login'
    # ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='base/login.html'),
        name='logout'
    ),
    # path('logoutmodal/', LogOutModalView.as_view(), name='logout-modal'),
    path('config/<int:pk>', UpdateBaseConfigView.as_view(), name='base-config'),
    path('load-data', LoadData, name='load-data'),


    path('update-app', UpdateApps, name='update-app'),
    path('install-app/<int:pk>/', InstallApps, name='install-app'),
    path('uninstall-app/<int:pk>/', UninstallApps, name='uninstall-app'),


    path('users', UserListView.as_view(), name='users'),
    path('user/add/', UserCreateView.as_view(), name='user-add'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', DeleteUser, name='user-delete'),
    path('user/change-password/<int:pk>', ChangePasswordForm, name='password-change'),
    path('user/change-password-confirm/<int:pk>', DoChangePassword, name='do-change-password'),

    path('products', ProductListView.as_view(), name='products'),
    path('product/add/', ProductCreateView.as_view(), name='product-add'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('Product/<int:pk>/update', ProductUpdateView.as_view(), name='product-update'),
    path('Product/<int:pk>/delete/', DeleteProduct, name='product-delete'),


    path('countries', CountryListView.as_view(), name='countries'),
    path('country/add/', CountryCreateView.as_view(), name='country-add'),
    path('country/<int:pk>/', CountryDetailView.as_view(), name='country-detail'),
    path('country/<int:pk>/update', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', DeleteCountry, name='country-delete'),

    path('companies', CompanyListView.as_view(), name='companies'),
    path('company/add/', CompanyCreateView.as_view(), name='company-add'),
    path('company/<int:pk>/', CompanyDetailView.as_view(), name='company-detail'),
    path('company/<int:pk>/update', CompanyUpdateView.as_view(), name='company-update'),
    path('company/<int:pk>/delete/', DeleteCompany, name='company-delete'),

    path('partners', CustomerListView.as_view(), name='partners'),
    path('provider', ProviderListView.as_view(), name='provider'),

    path('partner/add/', PartnerCreateView.as_view(), name='partner-add'),
    path('partner/<int:pk>/', PartnerDetailView.as_view(), name='partner-detail'),
    path('partner/<int:pk>/update', PartnerUpdateView.as_view(), name='partner-update'),
    path('partner/<int:pk>/delete/', DeletePartner, name='partner-delete'),

    path('product-category', ProductCategoryListView.as_view(), name='product-category'),
    path('product-category/add/', ProductCategoryCreateView.as_view(), name='product-category-add'),
    path('product-category/<int:pk>/', ProductCategoryDetailView.as_view(), name='product-category-detail'),
    path('product-category/<int:pk>/update', ProductCategoryUpdateView.as_view(), name='product-category-update'),
    path('product-category/<int:pk>/delete/', DeleteProductCategory, name='product-category-delete'),

    path('product-webcategory', ProductWebCategoryListView.as_view(), name='product-webcategory'),
    path('product-webcategory/add/', ProductWebCategoryCreateView.as_view(), name='product-webcategory-add'),
    path('product-webcategory/<int:pk>/', ProductWebCategoryDetailView.as_view(), name='product-webcategory-detail'),
    path('product-webcategory/<int:pk>/update', ProductWebCategoryUpdateView.as_view(), name='product-webcategory-update'),
    path('product-webcategory/<int:pk>/delete/', DeleteProductWebCategory, name='product-webcategory-delete'),

    path('logs', LogListView.as_view(), name='logs'),
    path('log/add/', LogCreateView.as_view(), name='log-add'),
    path('log/<int:pk>/', LogDetailView.as_view(), name='log-detail'),
    path('log/<int:pk>/update', LogUpdateView.as_view(), name='log-update'),
    path('log/<int:pk>/delete/', DeleteLog, name='log-delete'),

    path('crons', CronListView.as_view(), name='crons'),
    path('cron/add/', CronCreateView.as_view(), name='cron-add'),
    path('cron/<int:pk>/', CronDetailView.as_view(), name='cron-detail'),
    path('cron/<int:pk>/update', CronUpdateView.as_view(), name='cron-update'),
    path('cron/<int:pk>/delete/', DeleteCron, name='cron-delete'),

    path('currencies', CurrencyListView.as_view(), name='currencies'),
    path('currency/add/', CurrencyCreateView.as_view(), name='currency-add'),
    path('currency/<int:pk>/', CurrencyDetailView.as_view(), name='currency-detail'),
    path('currency/<int:pk>/update', CurrencyUpdateView.as_view(), name='currency-update'),
    path('currency/<int:pk>/delete/', DeleteCurrency, name='currency-delete'),


    path('apps', AppView.as_view(), name='apps'),

    # ====================== Rutas de Auto Completado ====================== #
    path(
        'partner/partner-autocomplete',
        PartnerAutoComplete.as_view(),
        name='partners-autocomplete'
    ),

    path('signup', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>', ActivateView.as_view(), name='activar'),
    path(
        'login/',
        LoginView.as_view(
            template_name='usercustom/login.html',
            # redirect_field_name='next',
            success_url = 'home'
        ),
        name='login'
    ),
    path(
        'logout',
        LogoutView.as_view(next_page='base:login'),
        name='logout'
    ),
    path('logoutmodal/', LogOutModalView.as_view(), name='logout-modal'),
    path('profile', login_required(ProfileView.as_view()), name='profile'),
    path(
        'changepasword',
        login_required(ChangePasswordView),
        name='change-password'
        ),
    path(
        'password-recovery',
        PasswordRecoveryView.as_view(),
        name='password-recovery'
    ),
    path(
        'password-recovery/<uidb64>/<token>',
        PasswordRecoveryView.as_view(),
        name='password-set'
    ),
    path('avatar', login_required(AvatarUpdateView.as_view()), name='avatar'),
]

pyerp/urls.py
"""Rutas de PyErp
"""
# Librerias Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views.static import serve

# Librerias de terceros
from apps.base.views import ActivateLanguageView

urlpatterns = [
    path('', include('apps.base.home_urls')),
    path('admin/', admin.site.urls),
    path('base/', include('apps.base.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT, }),
    # path('', include('apps.home.urls')),
]

urlpatterns += i18n_patterns(
    # path('', include('apps.base.home_urls')),
    # path('base/', include('apps.base.urls')),
    # path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path(
        '<language_code>/language/activate/',
        ActivateLanguageView.as_view(),
        name='activate_language'
    ),
)


with open('installed_apps.py', 'r') as ins_apps_file:
    for line in ins_apps_file.readlines():
        if line.strip() == 'apps.home':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.home.urls'))]
        else:
            _, app = line.split('.')
            urlpatterns += [path('%s/' % app.rstrip('\n'), include('%s.urls' % line.strip()))]

apps/base/models/base_config.py
# Librerias Django
from django.db import models
from django.urls import reverse

# Librerias en carpetas locales
from .company import PyCompany


class BaseConfig(models.Model):

    online = models.BooleanField('Online', default=False)
    main_company_id = models.ForeignKey(PyCompany, on_delete='cascade', null=True, blank=True)
    open_menu = models.BooleanField('Menu Abierto', default=True)
    load_data = models.BooleanField('Data Cargada', default=False)

    def get_absolute_url(self):
        return reverse('base:base-config', kwargs={'pk': self.pk})

    def dload_data(self):
        self.load_data = True

apps/base/models/country.py
# Librerias Django
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Librerias en carpetas locales
from .father import PyFather


class PyCountry(PyFather):
    name = models.CharField(_("Name"), max_length=40)

    def __str__(self):
        return format(self.name)

    def get_absolute_url(self):
        return reverse('base:country-detail', kwargs={'pk': self.pk})

apps/base/views/activate.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación globales
"""

# Librerias Django
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView

# Librerias en carpetas locales
from ..models import PyUser
from ..tokens import ACCOUNT_ACTIVATION_TOKEN


# ========================================================================== #
class ActivateView(RedirectView):
    """Esta clase activa a la persona cuando confirma el link enviado desde
    su correo
    """
    url = 'base:login'

    def get(self, request, *args, **kwargs):
        uidb64 = self.kwargs['uidb64']
        token = self.kwargs['token']
        url = self.get_redirect_url(*args, **kwargs)
        uid = force_text(urlsafe_base64_decode(uidb64))

        try:
            user = PyUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, PyUser.DoesNotExist):
            user = None

        token_valid = ACCOUNT_ACTIVATION_TOKEN.check_token(user, token)

        if user is not None and token_valid:
            user.is_active = True
            user.save()
            messages.success(
                self.request,
                _('Welcome, your account has been successfully activated. Please log in using your credentials.')
            )
        else:
            messages.error(
                self.request,
                _('The sign up confirm link is invalid. If your account is not yet active, use the password recovery link.')
            )

        return HttpResponseRedirect(reverse_lazy(url))

apps/base/views/activatelanguage.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación globales
"""

# Librerias Standard
from urllib.parse import urlparse

# Librerias Django
from django.shortcuts import redirect
from django.urls import resolve, reverse
from django.utils import translation
from django.views.generic.base import View


# ========================================================================== #
class ActivateLanguageView(View):
    ''' Clase para la activación de un lenguaje
    '''
    language_code = ''
    redirect_from = ''
    redirect_to = ''
    match = ''

    def get(self, request, *args, **kwargs):
        ''' Metodo para hacer switch en idiomas
        '''
        self.redirect_from = request.META.get('HTTP_REFERER', None) or '/'
        self.match = resolve(urlparse(self.redirect_from)[2])
        self.language_code = kwargs.get('language_code')
        self.redirect_to = self.match.namespace + ':' + self.match.url_name
        # self.redirect_to = self.match.url_name
        translation.activate(self.language_code)
        request.session[translation.LANGUAGE_SESSION_KEY] = self.language_code

        return redirect(reverse(self.redirect_to, kwargs=self.match.kwargs))

apps/base/views/avatar.py
# -*- coding: utf-8 -*-
"""
Vistas de la aplicación globales
"""
# Librerias Django
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView

# Librerias en carpetas locales
from ..forms import AvatarForm
from ..models import PyUser


# ========================================================================== #
class AvatarUpdateView(UpdateView):
    """Vista para editarar las sale
    """
    model = PyUser
    form_class = AvatarForm
    success_url = reverse_lazy('base:profile')

    def get_object(self, queryset=None):
        """
        Return the object the view is displaying.
        Require `self.queryset` and a `pk` or `slug` argument in the URLconf.
        Subclasses can override this to return any object.
        """
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        # pk = self.kwargs.get(self.pk_url_kwarg)
        pk = self.request.user.pk
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        if slug is not None and (pk is None or self.query_pk_and_slug):
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        if pk is None and slug is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(
                _("No %(verbose_name)s found matching the query") %
                {'verbose_name': queryset.model._meta.verbose_name}
            )
        return obj

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        usuario =PyUser.objects.get(pk=self.request.user.pk)

        if request.method == 'POST':
            form = AvatarForm(self.request.POST, self.request.FILES, instance=usuario)
            if form.is_valid():
                form.save()

        return redirect('profile')


# ========================================================================== #
# def avatar(request):
#     """Función para actualizar el avatar
#     """

#     usuario =PyUser.objects.get(pk=request.user.pk)

#     if request.method == 'POST':
#         form = AvatarForm(request.POST, request.FILES, instance=usuario)
#         if form.is_valid():
#             form.save()

    # return redirect('profile')

apps/base/views/base_config.py
# Librerias Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic.edit import UpdateView

# Librerias en carpetas locales
from ..models import BaseConfig


class UpdateBaseConfigView(LoginRequiredMixin, UpdateView):
    login_url = "login"
    model = BaseConfig
    template_name = 'base/form.html'
    fields = ['online', 'open_menu', 'main_company_id']


def LoadData(LoginRequiredMixin, request):
    state = BaseConfig.objects.get(pk=1).load_data
    if state:
        print("Ya existe Data")
    else:
        print("Cargamos")
    return render(request, 'base/ok.html')

apps/base/templates/base/apps.html
{% extends 'base/dashboard.html' %}
{% load staticfiles %}
{% block content %}
<section class="content">
  <div style="margin-top: 20px;"></div>
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
                  <!-- App -->
            {% for app in object_list %}
                  <div class="col-md-4">
                        <div class="info-box card-primary">
                          <span style="width: 120px;" class="info-box-icon {{ app.color }} elevation-1"><i class="fas {{ app.fa }}"></i></span>
                                  <div class="info-box-content">
                                    <span class="info-box-text"><b>{{ app.name }}</b> | {{ app.version }}</span>
                                    <span class="info-box-text">
                                      {{ app.author }} | {{ app.website }}
                                    </span>
                                      <span class="info-box-text">{{ app.description }}</span>
                                      {% if app.installed %}
                                      <a class="btn btn-danger float-right ml-1" href="{% url 'base:uninstall-app' app.id %}">Uninstall</a>
                                      {% else %}
                                      <a  class="btn btn-success float-right ml-1" href="{% url 'base:install-app' app.id %}">Install</a>
                                      {% endif %}
                                      <button class="btn btn-primary float-right" ><i class="fa fa-eye"></i></button>
                                  </div>
                        </div>
                  </div>
                  <!-- endApp -->
            {% endfor %}


          </div>
      </div>
  </section>

{% endblock %}

apps/base/templates/base/change_password.html
{% extends "base/dashboard.html" %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h3 class="text-center">Cambiar Contraseña</h3>
        <a href="{% url 'base:user-detail' pk %}" class="btn btn-danger">Descartar</a>
    </div>
    <div class="card-body">
        <form action="{% url 'base:do-change-password' pk %}" class="col-6 offset-3" method="POST">
            <div class="form-group row">
                <label for="new_password1" class="col-3 col-form-label">Contraseña Nueva</label>
                <div class="col-9"><input type="password" name="new_password1" id="new_password1" class="form-control" required></div>
            </div>
            <div class="form-group row">
                <label for="new_password2" class="col-3 col-form-label">Repetir Contraseña</label>
                <div class="col-9"><input type="password" name="new_password2" id="new_password2" class="form-control" required></div>
            </div>
            <div class="form-group-row">
                <div class="col-9 offset-3"><button type="submit" class="btn btn-primary">Cambiar Contraseña</button></div>
            </div>
            {% csrf_token %}
        </form>
        {% if error %}
        <div class="alert alert-danger mt-4 col-6 offset-3">{{error}}</div>
        {%endif%}
    </div>
</div>
{% endblock %}

apps/base/templates/base/detail.html
{% extends "base/dashboard.html" %}
{% load erp_tags %}

{% block content %}
<div class="card card-primary card-outline mt-2">
    <div class="card-header">
        <a href="{% url update_url object.pk %}" class="btn btn-success">{{ _("Edit") }}</a>
        <a href="{% url delete_url object.pk %}" class="btn btn-danger">{{ _("Delete") }}</a>
        {% for btn in buttons %}
        <a href="{{ btn.act }}" class="btn btn-{{btn.class}} float-right">{{btn.name}}</a>
        {% endfor %}
    </div>
    <div class="card-body">
        <form>
            <div class="form-row">
                {% for field in fields %}
                <div class="form-group col-sm-6">
                    <div class="row">
                        <label for="{{field.field}}" class="col-3 col-form-label">{{field.string}}</label>
                        <div class="col-9">
                            <input type="text" readonly class="form-control-plaintext" id="{{field.field}}" value="{{ object|get_obj_attr:field.field }}"/> 
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </form>
        <div class="row">
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
    $('.btn-danger').click(function (event) {
        event.preventDefault();
        if (confirm('{{ _("Are you sure you want to delete the form?") }}')){
            window.location = $(this)[0].href;
        }
    });
</script>
{% endblock %}

apps/base/templates/base/erp_footer.html
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.19
    </div>
    <strong>Copyright &copy; 2019 <a class="mylink" target="_blank" href="http://pyerp.cl">PyERP</a>.</strong> All rights
    reserved. Código Fuente:  <strong><a target="_blank" class="mylink" href="https://github.com/falconsoft3d/pyerp">github.com/falconsoft3d/pyerp</a></strong>
  </footer>

apps/base/templates/base/form.html
{% extends "base/dashboard.html" %}
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block content %}
<div class="card card-primary card-outline mt-2">
    <form method="post" class="form">
        <div class="card-header">
            {% buttons %}
            <a href="{{ back_url }}" class="btn btn-danger">{{ _("Discard") }}</a>
            <button type="submit" class="btn btn-primary">
                {{ _("Save") }}
            </button>
            {% endbuttons %}
        </div>
        <div class="card-body">
                {% csrf_token %}
                {% bootstrap_form form %}
        </div>
    </form>
</div>
{% endblock %}

apps/base/templates/base/index.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<link rel="stylesheet" href="{% static '/css/django.css' %}">

<link rel="shortcut icon" href="{% static '.' %}/dist/favicon.png" type="image/x-icon"/>

<style>

.image {
  opacity: 1;
  display: block;
  transition: .5s ease;
  backface-visibility: hidden;
}

.middle {
  transition: .5s ease;
  opacity: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  text-align: center;
}

.container:hover .image {
  opacity: 0.3;
}

.container:hover .middle {
  opacity: 1;
}

.text {
  background-color: #4CAF50;
  color: white;
  font-size: 16px;
  padding: 16px 32px;
}

.center {
    margin-left: auto;
    margin-right: auto;
    display: block;
    margin-top: 100px;
}
</style>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>PyERP</title>
</head>
    <body class="django-background">
        <div class="container">
                  <img src="{% static 'dist/favicon_white.png' %}" alt="Avatar" width="500" height="500" class="center image">
                  <div class="middle">
                      <a href="{% url 'base:home' %}"><div class="text">Login</div></a>
                  </div>
        </div>
    </body>
</html>

apps/base/templates/base/sidebar.html
{% load static %}
{% load erp_tags %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <img src="{% static 'dist/favicon_white.png' %}" alt="PyERP" style="opacity: .8; margin-left: 12px;" height="30px" >
        <span style="margin-left: 12px;" class="brand-text font-weight-light"><b>Py</b>ERP</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            {% if request.user.is_authenticated %}
                <div class="image">
                    <a href="{% url 'base:profile' %}" class="d-block"><img src="{{ request.user.avatar.url }}" id="user_avatar" class="img-circle elevation-2" alt="{{ request.user }}"></a>
                </div>
                <div class="info">
                    <a href="{% url 'base:profile' %}" class="d-block">{{ user }}</a>
                </div>
            {% endif %}
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item has-treeview">
                    <a href="{% url 'base:home' %}" class="nav-link"><i class="fa fa-home nav-icon"></i><p>{{ _('Home') }}</p></a>
                </li>
                {% for app in app_list|get_app_list %}
                    {% include app %}
                {% endfor %}
                <!-- Apps End -->
                {% if user.is_superuser %}
                    <!-- Configuracion Begin Sección solo para los administrdores -->
                    <!-- Apps Begin -->
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link"><i class="fa fa-microchip nav-icon"></i><p>{{ _('Apps') }}<i class="fas fa-angle-left right"></i><span class="badge badge-info right">{{ count_app }}</span></p></a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'base:apps' %}" class="nav-link"><i class="fa fa-users nav-icon"></i><p>{{ _('Apps') }}</p></a>
                            </li>
                            <li class="nav-item">
                              <a href="{% url 'base:update-app' %}" class="nav-link"><i class="fa fa-users nav-icon"></i><p>{{ _('Update') }}</p></a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link"><i class="fa fa-cogs nav-icon"></i><p>{{ _('Configuration') }}<i class="fas fa-angle-left right"></i></p></a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'base:users' %}" class="nav-link"><i class="fa fa-users nav-icon"></i><p>Usuarios</p></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'base:companies' %}" class="nav-link"><i class="fa fa-building nav-icon"></i><p>Compañias</p></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'base:base-config' 1 %}" class="nav-link"><i class="fa fa-cog nav-icon"></i><p>General</p></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'base:logs' %}" class="nav-link"><i class="fa fa-building nav-icon"></i><p>Log</p></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'base:crons' %}" class="nav-link"><i class="fa fa-building nav-icon"></i><p>Cron</p></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'base:countries' %}" class="nav-link"><i class="fa fa-building nav-icon"></i><p>{{ _('Countries') }}</p></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'base:load-data' %}" class="nav-link"><i class="fa fa-database nav-icon"></i><p>Cargar Datos Iniciales</p></a>
                            </li>
                        </ul>
                    </li>
                    <!-- Configuracion Begin Sección solo para los administrdores End -->
                {% endif %}
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>