apps/pos/urls.py
# Librerias Django
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

# Librerias en carpetas locales
from .views import PosIndex
from .views.pos import (
    DeletePos, PosCreateView, PosDetailView, PosListView, PosUpdateView)

app_name = 'pos'

urlpatterns = [
    url('pos-index', PosIndex, name='pos-index'),
    path('pos', PosListView.as_view(), name='pos'),
    path('pos/add/', PosCreateView.as_view(), name='pos-add'),
    path('pos/<int:pk>/', PosDetailView.as_view(), name='pos-detail'),
    path('pos/<int:pk>/update', PosUpdateView.as_view(), name='pos-update'),
    path('pos/<int:pk>/delete/', DeletePos, name='pos-delete'),
]

pyerp/urls.py
"""Rutas de PyErp
"""
# Librerias Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views.static import serve

# Librerias de terceros
from apps.base.views import ActivateLanguageView

urlpatterns = [
    path('', include('apps.base.home_urls')),
    path('admin/', admin.site.urls),
    path('base/', include('apps.base.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT, }),
    # path('', include('apps.home.urls')),
]

urlpatterns += i18n_patterns(
    # path('', include('apps.base.home_urls')),
    # path('base/', include('apps.base.urls')),
    # path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path(
        '<language_code>/language/activate/',
        ActivateLanguageView.as_view(),
        name='activate_language'
    ),
)


with open('installed_apps.py', 'r') as ins_apps_file:
    for line in ins_apps_file.readlines():
        if line.strip() == 'apps.home':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.home.urls'))]
        else:
            _, app = line.split('.')
            urlpatterns += [path('%s/' % app.rstrip('\n'), include('%s.urls' % line.strip()))]

apps/pos/models.py
# Librerias en carpetas locales
from .models.pos import PyPos

apps/pos/models/pos.py
# Librerias Django
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Librerias de terceros
from apps.base.models import PyFather


class PyPos(PyFather):
    name = models.CharField('Nombre', max_length=80)


    def get_absolute_url(self):
        return reverse('pos:pos-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return format(self.name)

apps/pos/views.py
from django.shortcuts import HttpResponse, render

def PosIndex(request):
    return render(request, 'pos/pos.html')

apps/pos/views/pos.py
# Librerias Django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

# Librerias en carpetas locales
from ..models.pos import PyPos

POS_FIELDS = [
            {'string': 'Nombre', 'field': 'name'},
        ]

POS_FIELDS_SHORT = ['name']


class PosListView(LoginRequiredMixin, ListView):
    model = PyPos
    template_name = 'base/list.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(PosListView, self).get_context_data(**kwargs)
        context['title'] = 'Puntos de Ventas'
        context['detail_url'] = 'pos:pos-detail'
        context['add_url'] = 'pos:pos-add'
        context['fields'] = POS_FIELDS
        return context

class PosDetailView(LoginRequiredMixin, DetailView):
    model = PyPos
    template_name = 'base/detail.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(PosDetailView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'pos:pos', 'name': 'Punto de Venta'}]
        context['update_url'] = 'pos:pos-update'
        context['delete_url'] = 'pos:pos-delete'
        context['fields'] = POS_FIELDS
        return context

class PosCreateView(LoginRequiredMixin, CreateView):
    model = PyPos
    fields = POS_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(PosCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Crear Puntos de Venta'
        context['breadcrumbs'] = [{'url': 'pos:pos', 'name': 'Punto de Venta'}]
        context['back_url'] = reverse('pos:pos')
        return context

class PosUpdateView(LoginRequiredMixin, UpdateView):
    model = PyPos
    fields = POS_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(PosUpdateView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'pos:pos', 'name': 'Punto de Venta'}]
        context['back_url'] = reverse('pos:pos-detail', kwargs={'pk': context['object'].pk})
        return context


@login_required(login_url="base:login")
def DeletePos(self, pk):
    pos = PyPos.objects.get(id=pk)
    pos.delete()
    return redirect(reverse('pos:pos'))

apps/pos/templates/pos/menu.html
<!-- Punto Venta Begin -->
<li class="nav-item has-treeview">
    <a href="#" class="nav-link">
      <i class="fa fa-desktop nav-icon"></i>
      <p>
         {{ _('POS') }}
        <i class="fas fa-angle-left right"></i>
      </p>
    </a>
    <ul class="nav nav-treeview">
      <li class="nav-item">
        <a href="{% url 'pos:pos' %}" class="nav-link">
          <i class="far fa-circle nav-icon"></i>
          <p>Cajas</p>
        </a>
      </li>

        <li class="nav-item">
        <a href="{% url 'pos:pos-index' %}" class="nav-link">
          <i class="far fa-circle nav-icon"></i>
          <p>POS</p>
        </a>
      </li>

    </ul>
  </li>
<!-- Inventario End -->

apps/pos/templates/pos/pos.html
{% load static %}
{% load erp_tags %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset ="UTF8">
  <title> {{ user|get_company_name }} | {{ user|get_company_slogan }} </title>
  <meta name="viewport" content="width = device-width">

  <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static '/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link rel="shortcut icon" href="{% static '.' %}/dist/favicon.png" type="image/x-icon"/>
  <link rel="stylesheet" href="{% static '/css/django.css' %}">

</head>
 <body class="django-background">
  
  <div class="my-container">
       <div class="row">
           <div class="col-sm-4 sql ">
               <div class="sql-inter">
                    <div class="sql-inter-sup" style="margin : 10px;">
                        <div class="row">
                        <div>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                  <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">1</a>
                                  </li>
                                  <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">2</a>
                                  </li>
                            </ul>


                        </div>
                        <div style="margin-left:100px;">
                            <a class="btn btn-danger" href="">+</a>
                            <a class="btn btn-danger" href="">-</a>
                        </div>

                        </div>
                    </div>
                    <div class="sql-inter-dow">

                        <div class="tab-content" id="myTabContent">
                                  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                      <div class="white-area">
                                          <p>PAN $2.000 x 2 = $4.000</p>
                                           <p>COCA COLA $2.000 x 2 = $4.000</p>
                                          <br><p>TOTAL = $4.000</p></br>
                                      </div>
                                  </div>
                                  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
                                  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
                                </div>

                    </div>
               </div>

           </div>
           <div class="col-sm-8 sql">
                <div class="sql-inter">
                    <div class="sql-inter-sup">
                        <a class="btn btn-primary" href="">HOME</a>
                        <a class="btn btn-primary" href="">LIQ</a>
                        <a class="btn btn-primary" href="">DRINK</a>

                        <div class="input-group stylish-input-group" style="margin-top:10px;">
                          <input type="text" id="searchProd" class="form-control" placeholder="Search">
                          <span class="input-group-addon">
                        </div>

                    </div>
                    <div class="sql-inter-dow">
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                        <div class="product django-background"></div>
                    </div>

               </div>
           </div>
       </div>
  </div>

  <style>
    .sql{

      }
      .sql-inter{
        margin-top:10px;
        background-color:#ECF0F1;
        min-height: 900px;
        padding-right: 0px !important;
        padding-left: 0px !important;
      }

      .sql-inter-sup{
        min-height: 90px;
        padding : 10px;
      }

      .sql-inter-dow{
        padding : 10px;
      }

      .white-area{
        min-height: 290px;
        background-color:#fff;
        width: 100%;
        padding: 5px;
        text-align: right !important;
      }

      .product{
            width: 120px;
            height: 120px;
            float:left;
            margin : 3px;
      }


  </style>
       
    <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 </body>
</html>